#!/bin/bash

while true; do
    # Test for Internet...
    wget -q --tries=10 --timeout=20 --spider http://google.com
    if [ $? -eq 127 ]; then
        echo 'wget: command not found, skipping net test, may/may not send mail.'
        break
    elif [ $? -eq 0 ]; then
        break
    else
        # Not connected, sleeping for a second
        sleep 1
    fi
done

# Now connected, run the script in virtual env
/usr/local/bin/pipenv run python3 ./send-mail.py
